services:
  - type: web
    name: form-docentes
    env: node
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run prod:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: form_docentes_db
          property: connectionString

databases:
  - name: form_docentes_db
    databaseName: form_docentes
    ipAllowList: [] # allow all 