services:
  - type: web
    name: form-docentes
    env: node
    region: oregon
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: form-docentes-db
          property: connectionString
          type: postgres
    dependsOn:
      - form-docentes-db

databases:
  - name: form-docentes-db
    region: oregon
    plan: free
    databaseName: form_docentes
    ipAllowList: [] 